#Work Section

projects:
  - {name: Typo International, folder: 'proj-1'}
  - {name: American Apparel, folder: 'proj-2'}
  - {name: Crispy Icons, folder: 'proj-3'}
  - {name: Flat Mobile UI/UX Concept, folder: 'proj-4'}
  - {name: Fresh It Up, folder: 'proj-5'}
  - {name: Timeline Page, folder: 'proj-6'}
  - {name: Weather Dashboard, folder: 'proj-7'}
  - {name: Stripes & Co, folder: 'proj-8'}





  #-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>'
  , logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>'
  , logo: 'logo2.png' }
- {avatar: 'face-jackiesaik.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>'
  , logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>'
  , logo: 'logo4.png'}
